# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 892443a642191c5818deadfa2e70ff4ca3b3e8412f5e5bb5763cf72c3b8f0d4049760aea6b554331d1cec1d0666e2811f3ffe346cabde91fa67a831e37398524

test:
  secret_key_base: 02b0558accbc76ef1f9f7e87c22ca5fba73080cbe0f16a28dc520dd94a5434792c622293d9f78ed2f755ec6aad7fe113216951c353609f3422397deb11f4653a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
